# Use a suitable OpenJDK 19 base image
FROM openjdk:19

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/task-service-0.0.1-SNAPSHOT.jar .

# Expose the port your application is listening on
EXPOSE 8080

# Command to run your application
CMD ["java", "-jar", "task-service-0.0.1-SNAPSHOT.jar"]
