version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb-container"
    ports:
      - "27017:27017"

  task-service:
    image: task-service-image
    ports:
      - "8080:8080"
    links:
      - mongodb


